#!/bin/bash
export DJANGO_SETTINGS_MODULE='config.settings'
export KAKAO_REST_API_KEY='dfda6b442a118074034d51dbc685ff4a'
# export PYTHONPATH='/var/app/current:$PYTHONPATH'
export RDS_DB_NAME='ebdb'
export RDS_HOSTNAME='localhost'
export RDS_PORT=5432
export RDS_PASSWORD='dosuri-back'
export RDS_USERNAME='postgres'
export SITE_URL='http://dosuri-env.eba-igc5wtjb.ap-northeast-2.elasticbeanstalk.com'
export AWS_ACCESS_KEY_ID='AKIAQLKLOTD7MFMOBQH5'
export AWS_SECRET_ACCESS_KEY='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'
export DOSURI_IMAGE_PUBLIC_KEY_ID='K3AE0DPLGOWKFV'
export DOSURI_IMAGE_PRIVATE_KEY_PATH='private_key.pem'
export HOST_DOMAIN='dosuri.site'
export ES_ENDPOINT='localhost'
export ES_USERNAME='elastic'
export ES_PASSWORD='dosuri'
export DEV_ENV='prod'

