version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d/
    restart: always
    depends_on:
      - app

  app:
    build: .
    restart: always

  celery-worker:
    build: .
    restart: always
    command: celery -A dosuri worker --loglevel=info
    depends_on:
      - app

  mq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

