POSITION_DOCTOR = 'doctor'
POSITION_THERAPIST = 'therapist'

HOSPITAL_ACTIVE = 'active'
HOSPITAL_INACTIVE = 'inactive'
HOSPITAL_PENDING = 'pending'

MAP_TYPE_PRICE = 'price'
MAP_TYPE_REVIEW = 'review'
