POSITION_DOCTOR = 'doctor'
POSITION_THERAPIST = 'therapist'

HOSPITAL_ACTIVE = 'active'
HOSPITAL_INACTIVE = 'inactive'
HOSPITAL_PENDING = 'pending'

MAP_TYPE_PRICE = 'price'
MAP_TYPE_REVIEW = 'review'

CONTACT_TYPE_REPRESENT = 'representative'
CONTACT_TYPE_COUNSEL = 'counseling'
CONTACT_TYPE_EVENT = 'event'
CONTACT_TYPE_AD = 'advertisement'

ATTACHMENT_TYPE_BANNER = 'banner'
ATTACHMENT_TYPE_PROFILE = 'profile'
ATTACHMENT_TYPE_INTRO = 'introduction'

DOCTOR_MALE = 'M'
DOCTOR_FEMALE = 'F'
