version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-images-upload"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jan5vpjr8msr"
s3_prefix = "sam-images-upload"
region = "ap-northeast-2"
profile = "dosuri"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
