# Generated by Django 4.1.1 on 2022-10-03 08:32

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models
import dosuri.user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('do', models.CharField(blank=True, default='', max_length=32)),
                ('city', models.CharField(blank=True, default='', max_length=32)),
                ('gun', models.CharField(blank=True, default='', max_length=32)),
                ('gu', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('thumbnail_url', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('introduction', models.CharField(blank=True, default='', max_length=512)),
                ('phone_no', models.CharField(blank=True, default='', max_length=32)),
                ('up_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_partner', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='dosuri.address')),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='InsuranceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('user_id', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insurance_log',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('is_custom', models.BooleanField(default=False)),
                ('domain', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospital_keyword',
            },
        ),
        migrations.CreateModel(
            name='HospitalKeywordAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_keyword_assoc', to='dosuri.hospital')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_keyword_assoc', to='dosuri.keyword')),
            ],
            options={
                'db_table': 'hospital_keyword_assoc',
            },
        ),
        migrations.CreateModel(
            name='HospitalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('url', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_image', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_image',
            },
        ),
        migrations.CreateModel(
            name='HospitalCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('monday', models.CharField(blank=True, default='', max_length=128)),
                ('tuesday', models.CharField(blank=True, default='', max_length=128)),
                ('wednesday', models.CharField(blank=True, default='', max_length=128)),
                ('thursday', models.CharField(blank=True, default='', max_length=128)),
                ('friday', models.CharField(blank=True, default='', max_length=128)),
                ('saturday', models.CharField(blank=True, default='', max_length=128)),
                ('sunday', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_calendar', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_calendar',
            },
        ),
        migrations.CreateModel(
            name='DoctorKeywordAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_keyword_assoc', to='dosuri.doctor')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_keyword_assoc', to='dosuri.keyword')),
            ],
            options={
                'db_table': 'doctor_keyword_assoc',
            },
        ),
        migrations.CreateModel(
            name='DoctorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('description', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_detail', to='dosuri.doctor')),
            ],
            options={
                'db_table': 'doctor_detail',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='dosuri.hospital'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('address_id', models.CharField(blank=True, default='', max_length=16)),
                ('birthday', models.DateTimeField(blank=True, default='')),
                ('sex', models.CharField(blank=True, default='', max_length=16)),
                ('is_real', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
