# Generated by Django 4.1.2 on 2022-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0005_alter_hospital_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='do',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='gu',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='gun',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
