# Generated by Django 4.1.2 on 2022-10-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0006_alter_address_city_alter_address_do_alter_address_gu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcalendar',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_calendar', to='dosuri.hospital'),
        ),
    ]
