# Generated by Django 4.1.2 on 2022-10-30 09:26

from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models
import dosuri.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0008_rename_doctordetail_doctordescription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='doctordescription',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='doctorkeywordassoc',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='hospitalcalendar',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='hospitalimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='hospitalkeywordassoc',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='insurancelog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='insurancelog',
            name='uuid',
            field=models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32),
        ),
        migrations.CreateModel(
            name='HospitalTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_treatment', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_treatment',
                'ordering': ['-id'],
            },
        ),
    ]
