# Generated by Django 4.1.2 on 2022-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0009_alter_address_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaltreatment',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
