# Generated by Django 4.1.2 on 2022-11-24 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0015_alter_user_managers_alter_address_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('up_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=None, null=True)),
                ('treat_count', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='dosuri.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('sensitive_agreement', models.BooleanField(default=False)),
                ('personal_agreement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_auth', to='dosuri.article')),
            ],
            options={
                'db_table': 'article_auth',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('up_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to='dosuri.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_comment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_assoc', to='dosuri.article')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_assoc', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assoc', to='dosuri.article')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assoc', to='dosuri.doctor')),
            ],
            options={
                'db_table': 'doctor_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AuthAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('path', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_article', to='dosuri.articleauth')),
            ],
            options={
                'db_table': 'auth_attach',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('up_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1200)),
                ('article_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_thread', to='dosuri.articlecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_thread', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_thread',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('treatment_effect', models.IntegerField(default=None, null=True)),
                ('doctor_kindness', models.IntegerField(default=None, null=True)),
                ('therapist_kindness', models.IntegerField(default=None, null=True)),
                ('clean_score', models.IntegerField(default=None, null=True)),
                ('content', models.CharField(max_length=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail', to='dosuri.article')),
            ],
            options={
                'db_table': 'article_detail',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('path', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_attach', to='dosuri.article')),
            ],
            options={
                'db_table': 'article_attach',
                'ordering': ['-id'],
            },
        ),
    ]
