# Generated by Django 4.1.2 on 2022-11-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0016_article_articleauth_articlecomment_hospitalassoc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
