# Generated by Django 4.1.2 on 2022-12-03 05:45

from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0017_article_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='dong',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='code',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='HospitalAddressAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_address_assoc', to='dosuri.address')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_address_assoc', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_address_assoc',
                'ordering': ['-id'],
            },
        ),
    ]
