# Generated by Django 4.1.2 on 2022-12-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0018_remove_address_street_address_dong_hospital_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='dong',
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
