# Generated by Django 4.1.2 on 2022-12-06 15:10

from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0019_remove_address_dong_hospital_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalTreatmentAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospital_treatment_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='InComplete', max_length=15),
        ),
        migrations.AddField(
            model_name='articleauth',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
        migrations.DeleteModel(
            name='HospitalAssoc',
        ),
        migrations.AddField(
            model_name='hospitaltreatmentassoc',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_treatment_assoc', to='dosuri.article'),
        ),
        migrations.AddField(
            model_name='hospitaltreatmentassoc',
            name='hospital_treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_treatment_assoc', to='dosuri.hospitaltreatment'),
        ),
    ]
