# Generated by Django 4.1.2 on 2022-12-07 16:23

from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0021_remove_hospitaltreatment_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('keyword', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'article_keyword',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleKeywordAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_treatment_assoc', to='dosuri.article')),
                ('article_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_treatment_assoc', to='dosuri.articlekeyword')),
            ],
            options={
                'db_table': 'article_keyword_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='HospitalTreatmentAssoc',
        ),
    ]
