# Generated by Django 4.1.2 on 2022-12-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0022_alter_hospitaltreatment_description'),
        ('dosuri', '0022_articlekeyword_articlekeywordassoc_and_more'),
    ]

    operations = [
    ]
