# Generated by Django 4.1.2 on 2022-12-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0023_merge_20221207_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='area',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
