# Generated by Django 4.1.2 on 2022-12-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0024_hospital_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleauth',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_auth', to='dosuri.article'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_detail', to='dosuri.article'),
        ),
        migrations.AlterField(
            model_name='articlekeywordassoc',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_keyword_assoc', to='dosuri.article'),
        ),
        migrations.AlterField(
            model_name='articlekeywordassoc',
            name='article_keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_keyword_assoc', to='dosuri.articlekeyword'),
        ),
        migrations.AlterField(
            model_name='authattach',
            name='article_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_attach', to='dosuri.articleauth'),
        ),
    ]
