# Generated by Django 4.1.2 on 2022-12-08 12:58

from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0025_alter_articleauth_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDoctorAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_doctor_assoc', to='dosuri.article')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_doctor_assoc', to='dosuri.doctor')),
            ],
            options={
                'db_table': 'article_doctor_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='DoctorAssoc',
        ),
    ]
