# Generated by Django 4.1.2 on 2022-12-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0026_articledoctorassoc_delete_doctorassoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalimage',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
    ]
