# Generated by Django 4.1.2 on 2022-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0028_remove_articledetail_content_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='article',
            name='treat_count',
        ),
        migrations.AddField(
            model_name='articledetail',
            name='cost',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='articledetail',
            name='treat_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='articleauth',
            name='status',
            field=models.CharField(default='InComplete', max_length=15),
        ),
    ]
