# Generated by Django 4.1.2 on 2022-12-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0029_remove_article_cost_remove_article_treat_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledetail',
            name='staff_kindness',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
