# Generated by Django 4.1.2 on 2022-12-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0030_articledetail_staff_kindness'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='subtitle',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
