# Generated by Django 4.1.2 on 2022-12-13 14:23

from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0031_doctor_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'doctor_keyword',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hospital_keyword',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(default='incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='articleauth',
            name='status',
            field=models.CharField(default='incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='doctorkeywordassoc',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_keyword_assoc', to='dosuri.doctorkeyword'),
        ),
        migrations.AlterField(
            model_name='hospitalkeywordassoc',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_keyword_assoc', to='dosuri.hospitalkeyword'),
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
