# Generated by Django 4.1.2 on 2022-12-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0032_doctorkeyword_hospitalkeyword_alter_article_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalkeyword',
            name='domain',
        ),
    ]
