# Generated by Django 4.1.2 on 2022-12-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0033_remove_hospitalkeyword_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalcalendar',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_calendar', to='dosuri.hospital'),
        ),
    ]
