# Generated by Django 4.1.2 on 2022-12-14 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0034_alter_hospitalcalendar_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalUserAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('is_up', models.BooleanField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_user_assoc', to='dosuri.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_user_assoc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
