# Generated by Django 4.1.2 on 2022-12-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0035_hospitaluserassoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaluserassoc',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='hospitaluserassoc',
            table='hospital_user_assoc',
        ),
    ]
