# Generated by Django 4.1.2 on 2022-12-15 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0037_hospitaluserassoc_hospital_user_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluserassoc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
