# Generated by Django 4.1.2 on 2022-12-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0039_hospitalsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='up_count',
        ),
    ]
