# Generated by Django 4.1.2 on 2022-12-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0040_remove_hospital_up_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='do',
        ),
        migrations.RemoveField(
            model_name='address',
            name='gu',
        ),
        migrations.RemoveField(
            model_name='address',
            name='gun',
        ),
        migrations.AddField(
            model_name='address',
            name='large_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='small_address',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
