# Generated by Django 4.1.2 on 2022-12-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0041_remove_address_city_remove_address_do_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='large_address',
            new_name='large_area',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='small_address',
            new_name='small_area',
        ),
    ]
