# Generated by Django 4.0.7 on 2022-08-26 10:13

from django.core.files import File
from django.db import migrations


def forward(app, schema_editor):
    PainArea = app.get_model('dosuri', 'PainArea')
    default_pain_areas = ['머리', '목', '어깨', '허리', '골반', '무릎', '손목', '발목', '관절', '그 외']
    for pain_area in default_pain_areas:
        PainArea.objects.get_or_create(
            name=pain_area
        )

def backward(app, schema_editor):
    PainArea = app.get_model('dosuri', 'PainArea')
    default_pain_areas = ['머리', '목', '어깨', '허리', '골반', '무릎', '손목', '발목', '관절', '그 외']
    for pain_area in default_pain_areas:
        PainArea.objects.delete(
            name=pain_area
        )


class Migration(migrations.Migration):
    dependencies = [
        ('dosuri', '0043_painarea_alter_insurancelog_user_id'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
