# Generated by Django 4.1.2 on 2022-12-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0044_create_default_painareas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painarea',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='painarea',
            table='pain_area',
        ),
    ]
