# Generated by Django 4.1.2 on 2022-12-20 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0045_alter_painarea_options_alter_painarea_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancelog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='insurancelog',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='insurance_log', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PainAreaUserAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pain_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_area_user_assoc', to='dosuri.painarea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_area_user_assoc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
