# Generated by Django 4.1.2 on 2022-12-20 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0047_alter_painareauserassoc_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='AddressUserAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_user_assoc', to='dosuri.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_user_assoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address_user_assoc',
                'ordering': ['-id'],
            },
        ),
    ]
