# Generated by Django 4.1.2 on 2022-12-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0048_user_phone_no_addressuserassoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_id',
        ),
    ]
