# Generated by Django 4.1.2 on 2022-12-26 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0049_alter_user_options_remove_user_address_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('name', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insurance',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceUserAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_user_assoc', to='dosuri.insurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_user_assoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insurance_user_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='InsuranceLog',
        ),
    ]
