# Generated by Django 4.0.7 on 2022-08-26 10:13

from django.core.files import File
from django.db import migrations


def forward(app, schema_editor):
    Insurance = app.get_model('dosuri', 'Insurance')
    Insurance.objects.get_or_create(
        name='현대해상'
    )

def backward(app, schema_editor):
    Insurance = app.get_model('dosuri', 'Insurance')
    Insurance.objects.delete(
        name='현대해상'
    )


class Migration(migrations.Migration):
    dependencies = [
        ('dosuri', '0050_insurance_insuranceuserassoc_delete_insurancelog'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
