# Generated by Django 4.1.2 on 2022-12-28 06:51

from django.db import migrations, models
import dosuri.common.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0052_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.common.models.generate_uuid, max_length=32)),
                ('bucket_name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=1024)),
                ('ref_uuid', models.CharField(max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attachment',
                'ordering': ['-id'],
            },
        ),
    ]
