# Generated by Django 4.1.2 on 2022-12-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0053_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authattach',
            name='article_auth',
        ),
        migrations.DeleteModel(
            name='ArticleAttach',
        ),
        migrations.DeleteModel(
            name='AuthAttach',
        ),
    ]
