# Generated by Django 4.1.2 on 2022-12-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dosuri', '0054_remove_authattach_article_auth_delete_articleattach_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ref_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ref_uuid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
