# Generated by Django 4.1.2 on 2022-12-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0055_attachment_ref_type_alter_attachment_ref_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ref_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='ref_uuid',
        ),
    ]
