# Generated by Django 4.1.2 on 2022-12-29 13:33

from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0056_remove_attachment_ref_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttachmentAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_attachment_assoc', to='dosuri.article')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_attachment_assoc', to='dosuri.attachment')),
            ],
            options={
                'db_table': 'article_attachment_assoc',
                'ordering': ['-id'],
            },
        ),
    ]
