# Generated by Django 4.1.2 on 2022-12-30 13:16

from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0058_authattachmentassoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAttachmentAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attachment_assoc', to='dosuri.attachment')),
            ],
            options={
                'db_table': 'doctor_attachment_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalAttachmentAssoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_attachment_assoc', to='dosuri.attachment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_attachment_assoc', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_attachment_assoc',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='thumbnail_url',
        ),
        migrations.DeleteModel(
            name='HospitalImage',
        ),
        migrations.AddField(
            model_name='doctorattachmentassoc',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_attachment_assoc', to='dosuri.doctor'),
        ),
    ]
