# Generated by Django 4.1.2 on 2023-01-02 11:15

from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0058_authattachmentassoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('category', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'treatment_category',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('keyword', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatmeny_keyword', to='dosuri.treatmentcategory')),
            ],
            options={
                'db_table': 'treatment_keyword',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='articlekeywordassoc',
            name='article_keyword',
        ),
        migrations.AlterField(
            model_name='articlekeywordassoc',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_keyword_assoc', to='dosuri.article'),
        ),
        migrations.DeleteModel(
            name='ArticleKeyword',
        ),
        migrations.AddField(
            model_name='articlekeywordassoc',
            name='treatment_keyword',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_keyword_assoc', to='dosuri.treatmentkeyword'),
            preserve_default=False,
        ),
    ]
