# Generated by Django 4.1.2 on 2023-01-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0059_doctorattachmentassoc_hospitalattachmentassoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
