# Generated by Django 4.1.2 on 2023-01-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0061_treatmentcategory_treatmentkeyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('modify_point', models.IntegerField(default=0)),
                ('total_point', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_point_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_point_history',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.user.models.generate_uuid, max_length=32)),
                ('content', models.CharField(default='', max_length=128)),
                ('is_new', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification',
                'ordering': ['-id'],
            },
        ),
    ]
