# Generated by Django 4.1.2 on 2023-01-04 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0063_remove_articlethread_mention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlethread',
            name='mention_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_thread_mention_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
