# Generated by Django 4.1.2 on 2023-01-09 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.community.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0066_userresignhistory_alter_usernotification_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.community.models.generate_uuid, max_length=32)),
                ('is_like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_like', to='dosuri.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_like',
                'ordering': ['-id'],
            },
        ),
    ]
