# Generated by Django 4.1.2 on 2023-01-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0067_articlelike'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlelike',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='One like by article'),
        ),
    ]
