# Generated by Django 4.1.2 on 2023-01-15 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0069_alter_treatmentkeyword_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tmp_review_username',
        ),
    ]
