# Generated by Django 4.1.2 on 2023-01-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0070_remove_user_tmp_review_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
