# Generated by Django 4.1.2 on 2023-01-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0072_hospital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
