# Generated by Django 4.1.2 on 2023-01-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0074_alter_hospital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='dosuri.hospital'),
        ),
    ]
