# Generated by Django 4.1.2 on 2023-02-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0076_alter_usernotification_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
