# Generated by Django 4.1.2 on 2023-02-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0077_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
