# Generated by Django 4.1.2 on 2023-03-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0079_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
