# Generated by Django 4.1.2 on 2023-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0080_useraddress_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
