# Generated by Django 4.1.2 on 2023-05-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0081_alter_hospital_latitude_alter_hospital_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='near_site',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
