# Generated by Django 4.1.2 on 2023-05-30 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0082_hospital_near_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reservation', to='dosuri.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hospital_reservation',
                'ordering': ['-id'],
            },
        ),
    ]
