# Generated by Django 4.1.2 on 2023-07-02 10:50

from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0085_usersetting_delete_userpersonalinformationagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='agree_marketing_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='agree_marketing_personal_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='agree_marketing_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='agree_marketing_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HospitalContactPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('contact_type', models.CharField(choices=[('representative', '대표 전화번호'), ('counseling', '상담 관리자 번호'), ('event', '이벤트 관리자 번호'), ('advertisement', '마케팅 담당자 이메일')], max_length=50)),
                ('contact_point', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_contact_point', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_contact_point',
                'ordering': ['-id'],
            },
        ),
    ]
