# Generated by Django 4.1.2 on 2023-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0086_alter_usersetting_agree_marketing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_ad',
            field=models.BooleanField(default=False),
        ),
    ]
