# Generated by Django 4.1.2 on 2023-07-30 08:58

from django.db import migrations, models
import django.db.models.deletion
import dosuri.hospital.models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0087_hospital_is_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalParkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, default=dosuri.hospital.models.generate_uuid, max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_parking_info', to='dosuri.hospital')),
            ],
            options={
                'db_table': 'hospital_parking_info',
                'ordering': ['-id'],
            },
        ),
    ]
