# Generated by Django 4.1.2 on 2023-08-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0088_hospitalparking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='hospital',
            name='parking_info',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='HospitalParkingInfo',
        ),
    ]
