# Generated by Django 4.1.2 on 2023-08-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0089_alter_doctor_options_hospital_parking_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='introduction',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
