# Generated by Django 4.1.2 on 2023-08-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0090_alter_hospital_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalattachmentassoc',
            name='attachment_type',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
