# Generated by Django 4.1.2 on 2023-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0091_hospitalattachmentassoc_attachment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='license_no',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='sex',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
