# Generated by Django 4.1.2 on 2023-10-29 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0092_doctor_license_no_doctor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalreservation',
            name='reservation_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalreservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
