# Generated by Django 4.1.2 on 2023-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosuri', '0093_hospitalreservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='website_address',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hospitalcalendar',
            name='lunch_time',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
