name: 🧪 Run Tests

on:
  push:
    branches:
      - '**'
      - "!master"
      - "!prod"

jobs:
  Test:
    name: CI Pipeline
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: dosuri
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Psql Client
        run: sudo apt-get install -y libpq-dev postgresql-client

      - name: Create Psql
        run: PGPASSWORD=dosuri psql -U postgres -h localhost -c 'CREATE DATABASE "dosuri-test"'

      - name: Run Tests
        run: make test
